export const sportsProducts = [
  { id: 1, name: "Genius Grand Edition English Willow Bat", category: "Cricket Bats", brand: "MRF", price: 8999, originalPrice: 12999, discount: 31, rating: 4.7, image: "https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?auto=format&fit=crop&w=900&q=80", sizes: ["SH", "Harrow"], colors: ["Natural", "Red"], stock: "In Stock", delivery: "Free Delivery", description: "Premium English willow cricket bat built for powerful stroke play.", isTrending: true, isBestSeller: true, createdAt: "2026-06-24" },
  { id: 2, name: "Ton Reserve Edition Kashmir Willow Bat", category: "Cricket Bats", brand: "SS", price: 3499, originalPrice: 5499, discount: 36, rating: 4.4, image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=900&q=80", sizes: ["SH", "6", "5"], colors: ["Natural", "Blue"], stock: "In Stock", delivery: "Free Delivery", description: "Balanced Kashmir willow bat for club and practice matches.", isTrending: true, isBestSeller: false, createdAt: "2026-06-18" },
  { id: 3, name: "Sunny Legend Cricket Bat", category: "Cricket Bats", brand: "SG", price: 4299, originalPrice: 6999, discount: 39, rating: 4.5, image: "https://images.unsplash.com/photo-1593766788306-28561086694e?auto=format&fit=crop&w=900&q=80", sizes: ["SH", "Harrow", "6"], colors: ["Natural", "Black"], stock: "Limited Stock", delivery: "Free Delivery", description: "Classic profile cricket bat with thick edges and responsive pickup.", isTrending: false, isBestSeller: true, createdAt: "2026-06-10" },
  { id: 4, name: "Pro Match Leather Cricket Ball Pack", category: "Cricket Balls", brand: "Kookaburra", price: 1299, originalPrice: 1999, discount: 35, rating: 4.6, image: "https://images.unsplash.com/photo-1600679472829-3044539ce8ed?auto=format&fit=crop&w=900&q=80", sizes: ["156g"], colors: ["Red", "White"], stock: "In Stock", delivery: "Free Delivery", description: "Durable leather cricket balls for match and academy training.", isTrending: true, isBestSeller: true, createdAt: "2026-06-27" },
  { id: 5, name: "Tournament White Cricket Ball", category: "Cricket Balls", brand: "SG", price: 799, originalPrice: 1299, discount: 38, rating: 4.3, image: "https://images.unsplash.com/photo-1629285483773-6b5cde2171d2?auto=format&fit=crop&w=900&q=80", sizes: ["156g"], colors: ["White"], stock: "In Stock", delivery: "Free Delivery", description: "White cricket ball made for limited overs matches and nets.", isTrending: false, isBestSeller: false, createdAt: "2026-05-28" },
  { id: 6, name: "Club Red Leather Cricket Ball", category: "Cricket Balls", brand: "DSC", price: 649, originalPrice: 999, discount: 35, rating: 4.1, image: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=900&q=80", sizes: ["156g"], colors: ["Red"], stock: "In Stock", delivery: "Free Delivery", description: "Reliable leather cricket ball for practice, schools, and weekend matches.", isTrending: false, isBestSeller: false, createdAt: "2026-05-20" },
  { id: 7, name: "Elite Batting Pads", category: "Batting Pads", brand: "Gray-Nicolls", price: 2999, originalPrice: 4999, discount: 40, rating: 4.5, image: "https://images.unsplash.com/photo-1624526267817-72919c433d82?auto=format&fit=crop&w=900&q=80", sizes: ["Adult", "Youth"], colors: ["White", "Red"], stock: "In Stock", delivery: "Free Delivery", description: "Lightweight batting pads with strong knee protection and comfort straps.", isTrending: true, isBestSeller: true, createdAt: "2026-06-22" },
  { id: 8, name: "Pro Guard Batting Pads", category: "Batting Pads", brand: "SS", price: 2199, originalPrice: 3499, discount: 37, rating: 4.3, image: "https://images.unsplash.com/photo-1624526267773-57040ad3c0db?auto=format&fit=crop&w=900&q=80", sizes: ["Adult", "Youth", "Junior"], colors: ["White", "Blue"], stock: "Limited Stock", delivery: "Free Delivery", description: "Comfort-focused batting pads for regular match practice.", isTrending: false, isBestSeller: false, createdAt: "2026-06-04" },
  { id: 9, name: "Premium Batting Gloves", category: "Batting Gloves", brand: "MRF", price: 1899, originalPrice: 2999, discount: 37, rating: 4.6, image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=900&q=80", sizes: ["Adult", "Youth"], colors: ["White", "Red"], stock: "In Stock", delivery: "Free Delivery", description: "Flexible batting gloves with split-finger protection and soft palm grip.", isTrending: true, isBestSeller: false, createdAt: "2026-06-26" },
  { id: 10, name: "Players Edition Batting Gloves", category: "Batting Gloves", brand: "DSC", price: 1499, originalPrice: 2499, discount: 40, rating: 4.2, image: "https://images.unsplash.com/photo-1593766788306-28561086694e?auto=format&fit=crop&w=900&q=80", sizes: ["Adult", "Youth", "Junior"], colors: ["White", "Navy"], stock: "In Stock", delivery: "Free Delivery", description: "Breathable batting gloves with reinforced protection for confident stroke play.", isTrending: false, isBestSeller: true, createdAt: "2026-06-12" },
  { id: 11, name: "Astrox Power Badminton Racket", category: "Badminton Rackets", brand: "Yonex", price: 3299, originalPrice: 5499, discount: 40, rating: 4.8, image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=900&q=80", sizes: ["G4"], colors: ["Black", "Red"], stock: "In Stock", delivery: "Free Delivery", description: "Head-heavy racket designed for attacking smashes and fast rallies.", isTrending: true, isBestSeller: true, createdAt: "2026-06-29" },
  { id: 12, name: "Turbo X Badminton Racket", category: "Badminton Rackets", brand: "Li-Ning", price: 2499, originalPrice: 3999, discount: 38, rating: 4.5, image: "https://images.unsplash.com/photo-1613918431703-aa50889e3be1?auto=format&fit=crop&w=900&q=80", sizes: ["G4", "G5"], colors: ["Blue", "Silver"], stock: "In Stock", delivery: "Free Delivery", description: "Lightweight badminton racket with quick handling and stable shaft response.", isTrending: false, isBestSeller: true, createdAt: "2026-06-17" },
  { id: 13, name: "Carbon Lite Badminton Racket", category: "Badminton Rackets", brand: "Decathlon", price: 1699, originalPrice: 2499, discount: 32, rating: 4.2, image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=900&q=80", sizes: ["G4"], colors: ["Black", "Yellow"], stock: "In Stock", delivery: "Free Delivery", description: "Beginner-friendly carbon racket with easy control and durable strings.", isTrending: false, isBestSeller: false, createdAt: "2026-05-30" },
  { id: 14, name: "Feather Shuttlecock Tube", category: "Shuttlecocks", brand: "Yonex", price: 999, originalPrice: 1499, discount: 33, rating: 4.6, image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=900&q=80", sizes: ["Pack of 12"], colors: ["White"], stock: "In Stock", delivery: "Free Delivery", description: "Tournament-grade feather shuttlecocks with accurate flight and speed.", isTrending: true, isBestSeller: true, createdAt: "2026-06-25" },
  { id: 15, name: "Nylon Shuttlecock Pack", category: "Shuttlecocks", brand: "Li-Ning", price: 549, originalPrice: 899, discount: 39, rating: 4.3, image: "https://images.unsplash.com/photo-1613918431703-aa50889e3be1?auto=format&fit=crop&w=900&q=80", sizes: ["Pack of 6"], colors: ["Yellow", "White"], stock: "In Stock", delivery: "Free Delivery", description: "Durable nylon shuttlecocks for daily practice and recreational games.", isTrending: false, isBestSeller: false, createdAt: "2026-06-01" },
  { id: 16, name: "FIFA Quality Training Football", category: "Footballs", brand: "Nivia", price: 1299, originalPrice: 2199, discount: 41, rating: 4.5, image: "https://images.unsplash.com/photo-1614632537190-23e4146777db?auto=format&fit=crop&w=900&q=80", sizes: ["5"], colors: ["White", "Blue"], stock: "In Stock", delivery: "Free Delivery", description: "Machine-stitched football with strong grip and consistent bounce.", isTrending: true, isBestSeller: true, createdAt: "2026-06-20" },
  { id: 17, name: "Predator Club Football", category: "Footballs", brand: "Adidas", price: 1799, originalPrice: 2999, discount: 40, rating: 4.7, image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=900&q=80", sizes: ["5"], colors: ["White", "Black", "Red"], stock: "In Stock", delivery: "Free Delivery", description: "Training football built for accuracy, durability, and everyday sessions.", isTrending: true, isBestSeller: false, createdAt: "2026-06-28" },
  { id: 18, name: "Street Play Football", category: "Footballs", brand: "Vector X", price: 699, originalPrice: 1099, discount: 36, rating: 4.1, image: "https://images.unsplash.com/photo-1579952363873-27f3bade9f55?auto=format&fit=crop&w=900&q=80", sizes: ["4", "5"], colors: ["Orange", "Black"], stock: "Limited Stock", delivery: "Free Delivery", description: "Tough football made for parks, streets, and casual play.", isTrending: false, isBestSeller: false, createdAt: "2026-05-26" },
  { id: 19, name: "Strike Training Football", category: "Footballs", brand: "Nike", price: 1599, originalPrice: 2499, discount: 36, rating: 4.4, image: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?auto=format&fit=crop&w=900&q=80", sizes: ["5"], colors: ["White", "Green"], stock: "In Stock", delivery: "Free Delivery", description: "Responsive football with textured panels for better touch.", isTrending: false, isBestSeller: true, createdAt: "2026-06-09" },
  { id: 20, name: "Attack Volleyball", category: "Volleyballs", brand: "Cosco", price: 849, originalPrice: 1299, discount: 35, rating: 4.2, image: "https://images.unsplash.com/photo-1592656094267-764a45160876?auto=format&fit=crop&w=900&q=80", sizes: ["Standard"], colors: ["Yellow", "Blue"], stock: "In Stock", delivery: "Free Delivery", description: "Soft-touch volleyball for school, beach, and indoor play.", isTrending: false, isBestSeller: true, createdAt: "2026-06-03" },
  { id: 21, name: "Tournament Volleyball", category: "Volleyballs", brand: "Nivia", price: 1199, originalPrice: 1899, discount: 37, rating: 4.4, image: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=900&q=80", sizes: ["Standard"], colors: ["White", "Blue"], stock: "In Stock", delivery: "Free Delivery", description: "Durable volleyball with excellent flight control and grip.", isTrending: true, isBestSeller: false, createdAt: "2026-06-16" },
  { id: 22, name: "Beach Volleyball Pro", category: "Volleyballs", brand: "Puma", price: 1399, originalPrice: 2299, discount: 39, rating: 4.3, image: "https://images.unsplash.com/photo-1592656094267-764a45160876?auto=format&fit=crop&w=900&q=80", sizes: ["Standard"], colors: ["Orange", "White"], stock: "In Stock", delivery: "Free Delivery", description: "Weather-ready volleyball with soft panels for outdoor games.", isTrending: false, isBestSeller: false, createdAt: "2026-05-29" },
  { id: 23, name: "Junior Cricket Starter Bat", category: "Cricket Bats", brand: "Decathlon", price: 1199, originalPrice: 1999, discount: 40, rating: 4.1, image: "https://images.unsplash.com/photo-1624526267942-ab0ff8a3e972?auto=format&fit=crop&w=900&q=80", sizes: ["3", "4", "5", "6"], colors: ["Natural", "Blue"], stock: "In Stock", delivery: "Free Delivery", description: "Lightweight starter bat for juniors learning cricket fundamentals.", isTrending: false, isBestSeller: false, createdAt: "2026-05-21" },
  { id: 24, name: "Match Ready Football", category: "Footballs", brand: "Puma", price: 1499, originalPrice: 2599, discount: 42, rating: 4.5, image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=900&q=80", sizes: ["5"], colors: ["Yellow", "Black"], stock: "In Stock", delivery: "Free Delivery", description: "Match-ready football with strong panel bonding and reliable grip.", isTrending: true, isBestSeller: true, createdAt: "2026-06-23" },
];

export const categoryOptions = ["Cricket Bats", "Cricket Balls", "Batting Pads", "Batting Gloves", "Badminton Rackets", "Shuttlecocks", "Footballs", "Volleyballs"];
export const brandOptions = [...new Set(sportsProducts.map((product) => product.brand))].sort();
export const ratingOptions = [4.5, 4.0, 3.5];
export const discountOptions = [50, 40, 30, 20];