import React from 'react'

function addToCart() {
  return (
    <div>addToCart <h1 className="">Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum, magni. Harum fugiat voluptate vel ab libero magni amet nobis debitis recusandae reiciendis consectetur ipsam aperiam modi asperiores iste, in atque, itaque quos saepe expedita incidunt commodi esse, beatae voluptatum! Odio, repellat. Dolores magni nesciunt quod sequi aut, aliquam optio blanditiis id corporis esse voluptas sunt doloremque mollitia? Saepe explicabo aliquid quis praesentium minus magni, modi consequuntur omnis nesciunt deleniti, cum cupiditate doloribus provident nemo voluptate voluptates corrupti! Consequuntur laudantium eius esse officiis, harum, dolores velit aperiam sunt cumque eum, voluptatum rem facilis alias deleniti quis optio animi maxime. Delectus doloribus assumenda aut iure vitae, culpa exercitationem temporibus eveniet quidem alias dicta consequuntur mollitia ut impedit itaque amet reprehenderit autem quis nesciunt sit libero iste ipsum. Nam nobis ullam velit nulla delectus amet fugiat! Necessitatibus, vel pariatur eligendi, ex quidem aut alias dolores atque consectetur eos blanditiis hic voluptatem ipsum dolorum veniam? Cupiditate, et tempore? Rerum aperiam quos a molestias, quas dolores aliquam distinctio! Sunt, repellendus! Quos blanditiis enim porro! Alias quam aperiam, facere esse non voluptatum eaque fugit inventore, recusandae, impedit blanditiis molestias cum quasi harum a. Vero exercitationem quibusdam nostrum enim, optio assumenda illum nulla corporis quod molestias. Deleniti nostrum beatae similique aliquid sequi illum officiis, tempore ab eum odit reiciendis voluptate cupiditate blanditiis sint neque possimus delectus dolor labore voluptatem sed pariatur ea vitae? Illo atque excepturi architecto distinctio nam fuga reprehenderit ex ratione minima repellendus quam, saepe iusto perspiciatis, libero quos, assumenda unde. Dolores veritatis voluptatum maxime libero possimus dolor distinctio autem, ullam, error impedit recusandae! Fugiat doloremque eaque tenetur omnis, praesentium, cumque ipsam consequuntur architecto dolorum similique nostrum laboriosam in libero enim ea? In iure repellendus maiores? Placeat sit in non rem doloremque numquam repellendus, dicta esse unde ea exercitationem delectus excepturi velit id! Voluptatem, aliquam.</h1>
    </div>
  )
}

export default addToCart