export const accessoriesProducts = [
  { id: 1, name: "Aviator Classic Sunglasses", category: "Sunglasses", brand: "Ray-Ban", price: 6499, originalPrice: 8990, discount: 28, rating: 4.7, image: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=900&q=80", colors: ["Gold", "Green"], stock: "In Stock", delivery: "Free Delivery", description: "Iconic aviator sunglasses with premium metal frame and UV protection.", isTrending: true, isBestSeller: true, createdAt: "2026-06-28" },
  { id: 2, name: "Sport Shield Sunglasses", category: "Sunglasses", brand: "Oakley", price: 7999, originalPrice: 11999, discount: 33, rating: 4.8, image: "https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Blue"], stock: "In Stock", delivery: "Free Delivery", description: "Performance sunglasses with wraparound fit and glare control.", isTrending: true, isBestSeller: false, createdAt: "2026-06-25" },
  { id: 3, name: "Wayfarer UV Protected Sunglasses", category: "Sunglasses", brand: "Fastrack", price: 1499, originalPrice: 2499, discount: 40, rating: 4.2, image: "https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Brown"], stock: "In Stock", delivery: "Free Delivery", description: "Trendy wayfarer sunglasses for everyday street and travel looks.", isTrending: false, isBestSeller: true, createdAt: "2026-06-08" },
  { id: 4, name: "Gradient Lens Sunglasses", category: "Sunglasses", brand: "Tommy Hilfiger", price: 3999, originalPrice: 6999, discount: 43, rating: 4.4, image: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?auto=format&fit=crop&w=900&q=80", colors: ["Brown", "Gold"], stock: "Limited Stock", delivery: "Free Delivery", description: "Premium gradient lens sunglasses with refined lifestyle styling.", isTrending: true, isBestSeller: false, createdAt: "2026-06-18" },
  { id: 5, name: "Round Retro Sunglasses", category: "Sunglasses", brand: "United Colors of Benetton", price: 1899, originalPrice: 3299, discount: 42, rating: 4.1, image: "https://images.unsplash.com/photo-1563903530908-afdd155d057a?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Silver"], stock: "In Stock", delivery: "Free Delivery", description: "Round retro sunglasses with lightweight comfort and sharp appeal.", isTrending: false, isBestSeller: false, createdAt: "2026-05-25" },
  { id: 6, name: "Classic Baseball Cap", category: "Caps", brand: "Nike", price: 999, originalPrice: 1699, discount: 41, rating: 4.4, image: "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80", colors: ["Black", "White"], stock: "In Stock", delivery: "Free Delivery", description: "Classic curved-brim cap with breathable cotton twill comfort.", isTrending: true, isBestSeller: true, createdAt: "2026-06-22" },
  { id: 7, name: "Performance Training Cap", category: "Caps", brand: "Adidas", price: 899, originalPrice: 1499, discount: 40, rating: 4.3, image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=80", colors: ["Navy", "White"], stock: "In Stock", delivery: "Free Delivery", description: "Lightweight training cap with sweat-wicking comfort.", isTrending: false, isBestSeller: true, createdAt: "2026-06-12" },
  { id: 8, name: "Logo Snapback Cap", category: "Caps", brand: "Puma", price: 799, originalPrice: 1299, discount: 38, rating: 4.1, image: "https://images.unsplash.com/photo-1534215754734-18e55d13e346?auto=format&fit=crop&w=900&q=80", colors: ["Red", "Black"], stock: "Limited Stock", delivery: "Free Delivery", description: "Streetwear snapback cap with bold logo detail and adjustable fit.", isTrending: true, isBestSeller: false, createdAt: "2026-06-15" },
  { id: 9, name: "Denim Casual Cap", category: "Caps", brand: "Levi's", price: 1199, originalPrice: 1999, discount: 40, rating: 4.2, image: "https://images.unsplash.com/photo-1514327605112-b887c0e61c0a?auto=format&fit=crop&w=900&q=80", colors: ["Blue", "Black"], stock: "In Stock", delivery: "Free Delivery", description: "Casual denim cap that pairs easily with street and weekend outfits.", isTrending: false, isBestSeller: false, createdAt: "2026-05-29" },
  { id: 10, name: "Outdoor Trekking Cap", category: "Caps", brand: "Wildcraft", price: 699, originalPrice: 1199, discount: 42, rating: 4.0, image: "https://images.unsplash.com/photo-1575428652377-a2d80e2277fc?auto=format&fit=crop&w=900&q=80", colors: ["Olive", "Grey"], stock: "In Stock", delivery: "Free Delivery", description: "Outdoor cap with durable fabric and comfortable travel-ready fit.", isTrending: false, isBestSeller: false, createdAt: "2026-05-18" },
  { id: 11, name: "Cushioned Ankle Socks Pack", category: "Socks", brand: "Nike", price: 799, originalPrice: 1299, discount: 38, rating: 4.5, image: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=900&q=80", colors: ["White", "Black"], stock: "In Stock", delivery: "Free Delivery", description: "Pack of cushioned ankle socks for training and daily comfort.", isTrending: true, isBestSeller: true, createdAt: "2026-06-27" },
  { id: 12, name: "Crew Length Sports Socks", category: "Socks", brand: "Adidas", price: 699, originalPrice: 1099, discount: 36, rating: 4.4, image: "https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&w=900&q=80", colors: ["White", "Grey"], stock: "In Stock", delivery: "Free Delivery", description: "Soft crew socks with ribbed arch support and sporty finish.", isTrending: false, isBestSeller: true, createdAt: "2026-06-11" },
  { id: 13, name: "No Show Socks Combo", category: "Socks", brand: "Puma", price: 599, originalPrice: 999, discount: 40, rating: 4.1, image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=900&q=80", colors: ["Black", "White", "Grey"], stock: "In Stock", delivery: "Free Delivery", description: "No-show socks combo with stretch comfort and secure heel grip.", isTrending: false, isBestSeller: false, createdAt: "2026-05-30" },
  { id: 14, name: "Premium Cotton Socks Pack", category: "Socks", brand: "Van Heusen", price: 499, originalPrice: 899, discount: 44, rating: 4.0, image: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Navy"], stock: "In Stock", delivery: "Free Delivery", description: "Premium cotton socks designed for office and everyday wear.", isTrending: false, isBestSeller: false, createdAt: "2026-05-22" },
  { id: 15, name: "Leather Bi-Fold Wallet", category: "Wallets", brand: "Hidesign", price: 2499, originalPrice: 3999, discount: 38, rating: 4.6, image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80", colors: ["Brown", "Tan"], stock: "In Stock", delivery: "Free Delivery", description: "Premium leather bi-fold wallet with refined grain and card slots.", isTrending: true, isBestSeller: true, createdAt: "2026-06-26" },
  { id: 16, name: "Slim Formal Wallet", category: "Wallets", brand: "Tommy Hilfiger", price: 1999, originalPrice: 3499, discount: 43, rating: 4.4, image: "https://images.unsplash.com/photo-1606503825008-909a67e63c3d?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Brown"], stock: "In Stock", delivery: "Free Delivery", description: "Slim formal wallet with premium finish and neat everyday storage.", isTrending: false, isBestSeller: true, createdAt: "2026-06-19" },
  { id: 17, name: "Casual Denim Wallet", category: "Wallets", brand: "Levi's", price: 999, originalPrice: 1799, discount: 44, rating: 4.1, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", colors: ["Blue", "Black"], stock: "Limited Stock", delivery: "Free Delivery", description: "Casual wallet with denim-inspired texture and compact storage.", isTrending: true, isBestSeller: false, createdAt: "2026-06-14" },
  { id: 18, name: "Textured Leather Wallet", category: "Wallets", brand: "Allen Solly", price: 1299, originalPrice: 2299, discount: 43, rating: 4.2, image: "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=80", colors: ["Brown", "Black"], stock: "In Stock", delivery: "Free Delivery", description: "Textured wallet for work, gifting, and polished daily carry.", isTrending: false, isBestSeller: false, createdAt: "2026-05-28" },
  { id: 19, name: "Reversible Leather Belt", category: "Belts", brand: "Van Heusen", price: 1499, originalPrice: 2499, discount: 40, rating: 4.4, image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Brown"], stock: "In Stock", delivery: "Free Delivery", description: "Reversible leather belt with sleek buckle and formal versatility.", isTrending: true, isBestSeller: true, createdAt: "2026-06-24" },
  { id: 20, name: "Formal Pin Buckle Belt", category: "Belts", brand: "Allen Solly", price: 1199, originalPrice: 1999, discount: 40, rating: 4.2, image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Tan"], stock: "In Stock", delivery: "Free Delivery", description: "Formal pin buckle belt with clean finish and durable construction.", isTrending: false, isBestSeller: true, createdAt: "2026-06-09" },
  { id: 21, name: "Rugged Outdoor Belt", category: "Belts", brand: "Woodland", price: 1399, originalPrice: 2299, discount: 39, rating: 4.3, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", colors: ["Brown", "Olive"], stock: "Limited Stock", delivery: "Free Delivery", description: "Rugged belt with outdoor-inspired buckle and sturdy strap.", isTrending: true, isBestSeller: false, createdAt: "2026-06-16" },
  { id: 22, name: "Casual Webbing Belt", category: "Belts", brand: "United Colors of Benetton", price: 899, originalPrice: 1499, discount: 40, rating: 4.0, image: "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=80", colors: ["Navy", "Green"], stock: "In Stock", delivery: "Free Delivery", description: "Casual webbing belt with easy adjustability and weekend styling.", isTrending: false, isBestSeller: false, createdAt: "2026-05-21" },
  { id: 23, name: "Urban Laptop Backpack", category: "Bags", brand: "Wildcraft", price: 2499, originalPrice: 3999, discount: 38, rating: 4.5, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Grey"], stock: "In Stock", delivery: "Free Delivery", description: "Durable laptop backpack with organized compartments and padded comfort.", isTrending: true, isBestSeller: true, createdAt: "2026-06-29" },
  { id: 24, name: "Travel Duffel Bag", category: "Bags", brand: "Skybags", price: 1999, originalPrice: 3499, discount: 43, rating: 4.3, image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80", colors: ["Blue", "Black"], stock: "In Stock", delivery: "Free Delivery", description: "Spacious duffel bag for gym, travel, and short weekend trips.", isTrending: false, isBestSeller: true, createdAt: "2026-06-17" },
  { id: 25, name: "Hardcase Cabin Trolley Bag", category: "Bags", brand: "American Tourister", price: 4999, originalPrice: 7999, discount: 38, rating: 4.6, image: "https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?auto=format&fit=crop&w=900&q=80", colors: ["Silver", "Black"], stock: "In Stock", delivery: "Free Delivery", description: "Cabin-size trolley bag with hard shell protection and smooth wheels.", isTrending: true, isBestSeller: true, createdAt: "2026-06-27" },
  { id: 26, name: "Training Gym Bag", category: "Bags", brand: "Nike", price: 2299, originalPrice: 3799, discount: 39, rating: 4.4, image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Red"], stock: "In Stock", delivery: "Free Delivery", description: "Compact gym bag with shoe pocket and easy-carry handles.", isTrending: false, isBestSeller: false, createdAt: "2026-06-03" },
  { id: 27, name: "Classic Waist Bag", category: "Bags", brand: "Puma", price: 1199, originalPrice: 1999, discount: 40, rating: 4.1, image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&w=900&q=80", colors: ["Black", "Grey"], stock: "Limited Stock", delivery: "Free Delivery", description: "Compact waist bag for travel, walks, and hands-free essentials.", isTrending: true, isBestSeller: false, createdAt: "2026-06-12" },
  { id: 28, name: "Premium Office Backpack", category: "Bags", brand: "Tommy Hilfiger", price: 3999, originalPrice: 6499, discount: 38, rating: 4.5, image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=80", colors: ["Navy", "Black"], stock: "In Stock", delivery: "Free Delivery", description: "Premium office backpack with clean styling and laptop protection.", isTrending: false, isBestSeller: true, createdAt: "2026-05-31" },
  { id: 29, name: "Outdoor Daypack", category: "Bags", brand: "Woodland", price: 1799, originalPrice: 2999, discount: 40, rating: 4.2, image: "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=900&q=80", colors: ["Olive", "Brown"], stock: "In Stock", delivery: "Free Delivery", description: "Outdoor daypack with rugged utility pockets and lightweight comfort.", isTrending: false, isBestSeller: false, createdAt: "2026-05-26" },
  { id: 30, name: "Logo Training Backpack", category: "Bags", brand: "Adidas", price: 1999, originalPrice: 3299, discount: 39, rating: 4.3, image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80", colors: ["Black", "White"], stock: "In Stock", delivery: "Free Delivery", description: "Sporty backpack with logo detail, laptop sleeve, and daily utility.", isTrending: true, isBestSeller: false, createdAt: "2026-06-20" },
];

export const categoryOptions = ["Sunglasses", "Caps", "Socks", "Wallets", "Belts", "Bags"];
export const brandOptions = [...new Set(accessoriesProducts.map((product) => product.brand))].sort();
export const colorOptions = ["Black", "White", "Brown", "Blue", "Grey", "Gold", "Green", "Tan", "Red", "Navy", "Olive", "Silver"];
export const ratingOptions = [4.5, 4.0, 3.5];
export const discountOptions = [50, 40, 30, 20];