export const clothingProducts = [
  { id: 1, name: "Supima Cotton Crew Neck T-Shirt", category: "T-Shirts", gender: "Men", brand: "Roadster", price: 699, originalPrice: 1299, discount: 46, rating: 4.4, image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL"], colors: ["Black", "White", "Olive"], isTrending: true, delivery: "Free Delivery", description: "Soft everyday cotton T-shirt with a clean crew neck and premium hand feel.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-12" },
  { id: 2, name: "Oversized Graphic Cotton T-Shirt", category: "T-Shirts", gender: "Women", brand: "Tokyo Talkies", price: 599, originalPrice: 1199, discount: 50, rating: 4.2, image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L"], colors: ["Pink", "White", "Lavender"], isTrending: true, delivery: "Free Delivery", description: "Relaxed-fit graphic tee styled for easy casual outfits and weekend layering.", availability: "In Stock", isBestSeller: false, isLimitedStock: true, createdAt: "2026-06-24" },
  { id: 3, name: "Slim Fit Oxford Shirt", category: "Shirts", gender: "Men", brand: "Allen Solly", price: 1299, originalPrice: 2299, discount: 43, rating: 4.5, image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Blue", "White", "Grey"], isTrending: false, delivery: "Free Delivery", description: "Crisp cotton oxford shirt with a polished slim fit for office and after-hours plans.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-05-28" },
  { id: 4, name: "Satin Regular Fit Shirt", category: "Shirts", gender: "Women", brand: "Mango", price: 1799, originalPrice: 2999, discount: 40, rating: 4.6, image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Cream", "Navy", "Wine"], isTrending: true, delivery: "Free Delivery", description: "Fluid satin shirt with a refined sheen and versatile smart-casual appeal.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-18" },
  { id: 5, name: "Stretch Skinny Fit Jeans", category: "Jeans", gender: "Men", brand: "Levi's", price: 2199, originalPrice: 3999, discount: 45, rating: 4.3, image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80", sizes: ["30", "32", "34", "36"], colors: ["Dark Blue", "Black"], isTrending: false, delivery: "Free Delivery", description: "Modern skinny jeans made with stretch denim for structure and comfort.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-06-02" },
  { id: 6, name: "High Rise Wide Leg Jeans", category: "Jeans", gender: "Women", brand: "ONLY", price: 1899, originalPrice: 3499, discount: 46, rating: 4.4, image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80", sizes: ["26", "28", "30", "32", "34"], colors: ["Light Blue", "Indigo"], isTrending: true, delivery: "Free Delivery", description: "High-rise wide leg denim that balances vintage character with a current silhouette.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-20" },
  { id: 7, name: "Chino Casual Shorts", category: "Shorts", gender: "Men", brand: "H&M", price: 899, originalPrice: 1699, discount: 47, rating: 4.1, image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=900&q=80", sizes: ["30", "32", "34", "36"], colors: ["Khaki", "Navy", "Olive"], isTrending: false, delivery: "Free Delivery", description: "Clean chino shorts with a tailored casual fit for warm-weather dressing.", availability: "In Stock", isBestSeller: false, isLimitedStock: true, createdAt: "2026-05-21" },
  { id: 8, name: "Denim Paperbag Shorts", category: "Shorts", gender: "Women", brand: "Zara", price: 1199, originalPrice: 2199, discount: 45, rating: 4.2, image: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L"], colors: ["Blue", "Black"], isTrending: false, delivery: "Free Delivery", description: "Paperbag waist denim shorts with easy volume and a flattering high-rise shape.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-06-08" },
  { id: 9, name: "Athletic Slim Track Pants", category: "Track Pants", gender: "Men", brand: "Nike", price: 1999, originalPrice: 3495, discount: 43, rating: 4.7, image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Grey"], isTrending: true, delivery: "Free Delivery", description: "Lightweight track pants with a tapered fit and quick-moving comfort.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-26" },
  { id: 10, name: "High Waist Training Joggers", category: "Track Pants", gender: "Women", brand: "Puma", price: 1599, originalPrice: 2999, discount: 47, rating: 4.4, image: "https://images.unsplash.com/photo-1506629905607-d9e297d5759d?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Sage", "Grey"], isTrending: true, delivery: "Free Delivery", description: "Training joggers with a supportive waistband and soft stretch knit fabric.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-06-15" },
  { id: 11, name: "Quilted Puffer Jacket", category: "Jackets", gender: "Men", brand: "Jack & Jones", price: 2999, originalPrice: 5999, discount: 50, rating: 4.5, image: "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Navy", "Olive"], isTrending: false, delivery: "Free Delivery", description: "Warm quilted jacket with a lightweight build and clean everyday styling.", availability: "In Stock", isBestSeller: true, isLimitedStock: true, createdAt: "2026-05-30" },
  { id: 12, name: "Cropped Denim Jacket", category: "Jackets", gender: "Women", brand: "Vero Moda", price: 2299, originalPrice: 4299, discount: 47, rating: 4.3, image: "https://images.unsplash.com/photo-1520975682031-a9a3f3a5db8f?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L"], colors: ["Blue", "White"], isTrending: true, delivery: "Free Delivery", description: "Cropped denim jacket with sharp seams and a fresh layered look.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-06-22" },
  { id: 13, name: "Dri-FIT Running T-Shirt", category: "Sportswear", gender: "Men", brand: "Adidas", price: 1399, originalPrice: 2499, discount: 44, rating: 4.6, image: "https://images.unsplash.com/photo-1556817411-31ae72fa3ea0?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Red", "Black", "Blue"], isTrending: true, delivery: "Free Delivery", description: "Breathable running top designed to keep pace through training and travel.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-27" },
  { id: 14, name: "Seamless Training Co-Ord Set", category: "Sportswear", gender: "Women", brand: "Reebok", price: 2499, originalPrice: 4999, discount: 50, rating: 4.5, image: "https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L"], colors: ["Teal", "Black", "Mauve"], isTrending: true, delivery: "Free Delivery", description: "Performance-ready training set with smooth stretch and a sculpted fit.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-25" },
  { id: 15, name: "Heavyweight Pocket T-Shirt", category: "T-Shirts", gender: "Men", brand: "H&M", price: 799, originalPrice: 1499, discount: 47, rating: 4.0, image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL"], colors: ["Charcoal", "Beige", "White"], isTrending: false, delivery: "Free Delivery", description: "Heavyweight tee with a sturdy pocket detail and clean everyday drape.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-05-18" },
  { id: 16, name: "Ribbed Crop T-Shirt", category: "T-Shirts", gender: "Women", brand: "ONLY", price: 649, originalPrice: 1299, discount: 50, rating: 4.1, image: "https://images.unsplash.com/photo-1485968579580-b6d095142e6e?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L"], colors: ["Black", "Mint", "Ivory"], isTrending: false, delivery: "Free Delivery", description: "Ribbed cropped T-shirt with stretch comfort and a neat fitted shape.", availability: "In Stock", isBestSeller: false, isLimitedStock: true, createdAt: "2026-06-01" },
  { id: 17, name: "Checked Flannel Shirt", category: "Shirts", gender: "Men", brand: "Roadster", price: 999, originalPrice: 2199, discount: 55, rating: 4.2, image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL", "XXL"], colors: ["Red", "Green", "Blue"], isTrending: true, delivery: "Free Delivery", description: "Soft brushed flannel shirt with a classic checked pattern and relaxed feel.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-06-21" },
  { id: 18, name: "Linen Blend Resort Shirt", category: "Shirts", gender: "Women", brand: "Zara", price: 1599, originalPrice: 2799, discount: 43, rating: 4.4, image: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L", "XL"], colors: ["White", "Tan", "Coral"], isTrending: false, delivery: "Free Delivery", description: "Airy linen blend shirt with a relaxed collar and refined vacation mood.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-05-25" },
  { id: 19, name: "Relaxed Straight Jeans", category: "Jeans", gender: "Men", brand: "Levi's", price: 2499, originalPrice: 4499, discount: 44, rating: 4.6, image: "https://images.unsplash.com/photo-1511105043137-7e66f28270e3?auto=format&fit=crop&w=900&q=80", sizes: ["30", "32", "34", "36", "38"], colors: ["Indigo", "Blue"], isTrending: true, delivery: "Free Delivery", description: "Straight-leg denim with a relaxed thigh and timeless five-pocket styling.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-29" },
  { id: 20, name: "Mom Fit Ankle Jeans", category: "Jeans", gender: "Women", brand: "Mango", price: 2099, originalPrice: 3799, discount: 45, rating: 4.5, image: "https://images.unsplash.com/photo-1582418702059-97ebafb35d09?auto=format&fit=crop&w=900&q=80", sizes: ["26", "28", "30", "32"], colors: ["Vintage Blue", "Black"], isTrending: false, delivery: "Free Delivery", description: "Ankle-length mom jeans with a sculpted high rise and vintage-inspired wash.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-06-11" },
  { id: 21, name: "Performance Running Shorts", category: "Shorts", gender: "Men", brand: "Puma", price: 1099, originalPrice: 1999, discount: 45, rating: 4.3, image: "https://images.unsplash.com/photo-1507680434567-5739c80be1ac?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Blue"], isTrending: true, delivery: "Free Delivery", description: "Lightweight running shorts with breathable panels and a secure inner brief.", availability: "In Stock", isBestSeller: false, isLimitedStock: true, createdAt: "2026-06-23" },
  { id: 22, name: "Cotton Lounge Shorts", category: "Shorts", gender: "Women", brand: "Tokyo Talkies", price: 549, originalPrice: 999, discount: 45, rating: 4.0, image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Lilac", "Grey", "Black"], isTrending: false, delivery: "Free Delivery", description: "Soft cotton lounge shorts with an easy waistband and everyday comfort.", availability: "In Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-05-16" },
  { id: 23, name: "Logo Tape Track Pants", category: "Track Pants", gender: "Men", brand: "Adidas", price: 1899, originalPrice: 3299, discount: 42, rating: 4.4, image: "https://images.unsplash.com/photo-1571731956672-f2b94d7dd0cb?auto=format&fit=crop&w=900&q=80", sizes: ["S", "M", "L", "XL"], colors: ["Black", "Navy"], isTrending: false, delivery: "Free Delivery", description: "Sport-inspired track pants with logo tape detailing and a tapered leg.", availability: "Out of Stock", isBestSeller: false, isLimitedStock: false, createdAt: "2026-04-30" },
  { id: 24, name: "Light Support Sports Bra", category: "Sportswear", gender: "Women", brand: "Adidas", price: 1199, originalPrice: 2299, discount: 48, rating: 4.3, image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=900&q=80", sizes: ["XS", "S", "M", "L", "XL"], colors: ["Black", "Blue", "Pink"], isTrending: true, delivery: "Free Delivery", description: "Light-support sports bra with a soft elastic band and smooth studio-ready fabric.", availability: "In Stock", isBestSeller: true, isLimitedStock: false, createdAt: "2026-06-19" },
];

export const categoryOptions = ["T-Shirts", "Shirts", "Jeans", "Shorts", "Track Pants", "Jackets", "Sportswear"];
export const genderOptions = ["Men", "Women"];
export const brandOptions = [...new Set(clothingProducts.map((product) => product.brand))].sort();
export const ratingOptions = [4.5, 4.0, 3.5];
export const discountOptions = [50, 40, 30, 20];